version: '3.7'
services:
  postgresql:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2334
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped
    platform: linux/amd64
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    platform: linux/amd64
  servicereg:
    image: ofkodat/servicereg:latest
    container_name: servicereg
    ports:
      - "8762:8761"
    depends_on:
      - rabbitmq
      - zipkin
      - postgresql
      - pgadmin
    networks:
      - postgres
      - microservice-network
    platform: linux/amd64

  companyms:
    image: ofkodat/companyms:latest
    container_name: company
    ports:
      - 8081:8081
    depends_on:
      - servicereg

    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    platform: linux/amd64
  jobms:
    image: ofkodat/jobms:latest
    container_name: job
    ports:
      - 8082:8082
    depends_on:
      - servicereg

    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka
    platform: linux/amd64


  reviewms:
    image: ofkodat/reviewms:latest
    container_name: review
    ports:
      - 8083:8083
    depends_on:
      - servicereg

    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    platform: linux/amd64

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin2
    ports:
      - 9411:9411
    networks:
      - microservice-network
      - postgres
    platform: linux/amd64
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - microservice-network
      - postgres
    platform: linux/amd64
  gatewayms:
    image: ofkodat/gateway:latest
    ports:
      - 8084:8084
    depends_on:
      - servicereg
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    platform: linux/amd64
networks:
  microservice-network:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: